import Head from "next/head";
import { useState } from "react";
import { Poppins } from "next/font/google";
import styles from "../../styles/Home.module.scss";
import { useTranslation } from "next-i18next";
import fetchItemsById from "../components/QueryItemTypes/QueryItemTypes";
import { ItemList, length_recipes } from "../components/ItemList/ItemsList.jsx";
import { store_file } from "../services/data-service.jsx";
import { Filter } from "../components/Filter/Filter.jsx";
import { Header } from "../components/Header/Header.jsx";
import "./i18n";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

const Home = () => {
    const { t } = useTranslation("common");
    const [selectedType, setSelectedType] = useState(null);

    const handleLogClick = async () => {
        try {
            fetchItemsById();
        } catch (error) {
            console.error("Error fetching and processing data:", error);
        }
    };

    const handleTypeFilter = (types) => {
        console.log("Filtering items by types:", types);
        setSelectedType(types);
        // fetchItemsById(types);
    };

    return (
        <>
            <Head>
                <title>{t("common:WakfuKi")}</title>
                <meta
                    name="description"
                    content={t("common:Generated by create next app")}
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${poppins.className}`}>
                <Header></Header>
                <div className={styles["global-container"]}>
                    <Filter
                        handleLogClick={handleLogClick}
                        length_recipes={length_recipes}
                        store_file={store_file}
                        handleTypeFilter={handleTypeFilter}
                    ></Filter>
                    <div className={styles["item-list"]}>
                        <h3>{t("common:Item lists")}</h3>
                        {selectedType != null && (
                            <ItemList
                                key={selectedType.toString()}
                                selectedType={selectedType}
                            />
                        )}
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;
